### ISSUE TITLE
Throw a calls-stack details  Exceptions Msg  when  Calling Service (WebApi) project 'Sale By Id=5' endpoints which(SaleId=5) is not existed  at Sales DB table 

### ISSUE THREAD

**Issue by tutul2010** [matthewrenze/clean-architecture-demo#14]
Hi _@matthewrenze_ ,

Thanks for your wonderful PS course and code repo. 
I am playing around urs code base and found a handle exception which were  showing at swagger page, That   Exception Msg was not properly handled in sale middleware-application layer code .
_Testcase_ (Negative )
Calling API End-points -_https://localhost:7001/api/sales/5_
Above SaleId=5 was not present at Sales DB table and thrown a calls-stack exception msg at swagger page as response. It should be  handle in code and return a friendly Msg as response. Attached Screenshot as below
![image](https://github.com/matthewrenze/clean-architecture-demo/assets/13733464/078c948a-37f5-497e-9c11-861e6595aaba)

Thanks again for code.

Regards,
Tutul

**Comment by matthewrenze** [comment]
Tutul,

Thank you for pointing out the missing exception handling. 

To keep the code as simple as possible, for teaching purposes, I intentionally left out exception handling, logging, authentication, validation, etc. While I would expect all of these aspects to be present in a real-world production application, they were outside of the scope of the topics I was specifically trying to teach in this course.

So, if it's alright with you, I'll close this open issue -- since I do not plan to implement exception handling in this educational project. However, we'll leave this closed issue with our conversation available here for others who may have the same question or concern.

Thanks!

Matthew
